# This file contains values from Cookiecutter

default_context:
  project_name: "fisher-acm"
  project_description: "Awesome `fisher-acm` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "ems"
  license: "GNU GPL v3.0"
  version: "0.0.1"
  github_name: "boussoffara"
  email: "alaeddine@easymedstat.com"
