name: Run Tests
on: [push, pull_request]
jobs:
  build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install tox
      run: pip3 install tox
    - name: Run tox
      run: tox
