name: Run Tests
on: [push, pull_request]
jobs:
  build:
    name: Test build on ${{ matrix.os }} py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.8", "3.9", "3.10"]
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: pip3 install tox
    - name: Run tox
      run: tox
